arrowParens = "avoid"
bracketSpacing = true
insertPragma = false
jsxBracketSameLine = false
printWidth = 80.0
proseWrap = "preserve"
requirePragma = false
semi = false
singleQuote = true
tabWidth = 2.0
trailingComma = "es5"
useTabs = false
